project_id = "cmcvkmttlrjahpxsotyr"

[functions.verify-admin]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.anyflow-ai]
verify_jwt = false

[functions.generate-blog-posts]
verify_jwt = false
